name: Deploy to InfinityFree
on:
  push:
    branches:
      - main  # or 'master' depending on your default branch name

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftpupload.net }}
        username: ${{ secrets.if0_41512777 }}
        password: ${{ secrets.2Earnit2 }}
        server-dir: ./htdocs/  # InfinityFree requires files in htdocs